/**
 * Generates the per-app token layer from design-tokens/tokens.js:
 *   - src/app/tokens.css   web   — CSS variables + Tailwind v4 `@theme`
 *   - rnapp/global.css     rnapp — NativeWind input CSS + CSS variables
 *   - rnapp/lib/theme.ts   rnapp — runtime typed tokens (shadows, motion, …)
 *
 * Keeps both apps in lockstep with a single source of truth. Run from anywhere:
 *   node design-tokens/build-theme.mjs
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const tokens = require("./tokens.js");

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const WARNING = "GENERATED by design-tokens/build-theme.mjs — do not edit by hand.";

/** Indent each line of an array by two spaces and join. */
const block = (lines) => lines.map((l) => "  " + l).join("\n");
/** `--name: value;` declarations from a flat color map. */
const colorDecls = (map) => block(Object.entries(map).map(([k, v]) => `--${k}: ${v};`));

/* ----------------------------- web: tokens.css ---------------------------- */

const colorThemeMap = block(
  Object.keys(tokens.colors.light).map((k) => `--color-${k}: hsl(var(--${k}));`)
);
const radiusTheme = block(
  ["sm", "md", "lg", "xl"].map((k) => `--radius-${k}: ${tokens.radius[k]}px;`)
);
const fontTheme = block([
  `--font-sans: ${tokens.fontFamily.sans.web.join(", ")};`,
  `--font-mono: ${tokens.fontFamily.mono.web.join(", ")};`,
]);
const textTheme = block(
  Object.entries(tokens.typography).flatMap(([name, t]) => [
    `--text-${name}: ${t.fontSize}px;`,
    `--text-${name}--line-height: ${t.lineHeight}px;`,
    `--text-${name}--font-weight: ${t.fontWeight};`,
  ])
);
const shadowTheme = block(
  Object.entries(tokens.shadows).map(([name, s]) => `--shadow-${name}: ${s.web};`)
);

const webCss = `/* ${WARNING} */

:root {
${colorDecls(tokens.colors.light)}
}

.dark {
${colorDecls(tokens.colors.dark)}
}

@theme inline {
${colorThemeMap}
}

@theme {
${radiusTheme}

${fontTheme}

${textTheme}

${shadowTheme}
}
`;

/* --------------------------- rnapp: global.css ---------------------------- */

const rnCss = `/* ${WARNING} */
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
${colorDecls(tokens.colors.light)}
}

.dark:root {
${colorDecls(tokens.colors.dark)}
}
`;

/* -------------------------- rnapp: lib/theme.ts --------------------------- */

const rnTheme = {
  radius: tokens.radius,
  fontFamily: {
    ...tokens.fontFamily.sans.native,
    mono: tokens.fontFamily.mono.native.regular,
  },
  fontWeight: Object.fromEntries(
    Object.entries(tokens.fontWeight).map(([k, v]) => [k, String(v)])
  ),
  typography: Object.fromEntries(
    Object.entries(tokens.typography).map(([k, v]) => [
      k,
      { fontSize: v.fontSize, lineHeight: v.lineHeight, fontWeight: String(v.fontWeight) },
    ])
  ),
  shadows: Object.fromEntries(
    Object.entries(tokens.shadows).map(([k, v]) => [k, v.native])
  ),
  zIndex: tokens.zIndex,
  motion: tokens.motion,
};

const rnTs = `/* ${WARNING} */
/**
 * Runtime design tokens for the rnapp (Expo / NativeWind).
 * Prefer NativeWind classNames for styling; use this object when you need raw
 * values at runtime — shadow style objects, motion timings, z-index.
 */
export const theme = ${JSON.stringify(rnTheme, null, 2)} as const;

export type Theme = typeof theme;
`;

/* --------------------------------- write --------------------------------- */

for (const [rel, content] of [
  ["src/app/tokens.css", webCss],
  ["rnapp/global.css", rnCss],
  ["rnapp/lib/theme.ts", rnTs],
]) {
  const abs = resolve(root, rel);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
  console.log(`  ✓ ${rel}`);
}
console.log("design tokens generated.");
