/* GENERATED by design-tokens/build-theme.mjs — do not edit by hand. */
/**
 * Runtime design tokens for the rnapp (Expo / NativeWind).
 * Prefer NativeWind classNames for styling; use this object when you need raw
 * values at runtime — shadow style objects, motion timings, z-index.
 */
export const theme = {
  "radius": {
    "sm": 6,
    "md": 8,
    "lg": 10,
    "xl": 14,
    "full": 9999
  },
  "fontFamily": {
    "regular": "Geist_400Regular",
    "medium": "Geist_500Medium",
    "semibold": "Geist_600SemiBold",
    "bold": "Geist_700Bold",
    "mono": "GeistMono_400Regular"
  },
  "fontWeight": {
    "regular": "400",
    "medium": "500",
    "semibold": "600",
    "bold": "700"
  },
  "typography": {
    "display": {
      "fontSize": 30,
      "lineHeight": 36,
      "fontWeight": "600"
    },
    "title": {
      "fontSize": 24,
      "lineHeight": 32,
      "fontWeight": "600"
    },
    "heading": {
      "fontSize": 20,
      "lineHeight": 28,
      "fontWeight": "600"
    },
    "subheading": {
      "fontSize": 16,
      "lineHeight": 24,
      "fontWeight": "600"
    },
    "body": {
      "fontSize": 14,
      "lineHeight": 20,
      "fontWeight": "400"
    },
    "label": {
      "fontSize": 13,
      "lineHeight": 16,
      "fontWeight": "500"
    },
    "caption": {
      "fontSize": 12,
      "lineHeight": 16,
      "fontWeight": "400"
    }
  },
  "shadows": {
    "xs": {
      "shadowColor": "#000000",
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowOpacity": 0.05,
      "shadowRadius": 2,
      "elevation": 1
    },
    "sm": {
      "shadowColor": "#000000",
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowOpacity": 0.1,
      "shadowRadius": 3,
      "elevation": 2
    },
    "md": {
      "shadowColor": "#000000",
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowOpacity": 0.1,
      "shadowRadius": 6,
      "elevation": 4
    },
    "lg": {
      "shadowColor": "#000000",
      "shadowOffset": {
        "width": 0,
        "height": 4
      },
      "shadowOpacity": 0.1,
      "shadowRadius": 12,
      "elevation": 8
    }
  },
  "zIndex": {
    "dropdown": 1000,
    "sticky": 1100,
    "overlay": 1200,
    "modal": 1300,
    "popover": 1400,
    "toast": 1500
  },
  "motion": {
    "duration": {
      "fast": 150,
      "normal": 200,
      "slow": 300
    },
    "easing": {
      "standard": "cubic-bezier(0.2, 0, 0, 1)"
    }
  }
} as const;

export type Theme = typeof theme;
